GET http://localhost:5000/users
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOWUzNDU1NWExZGE4YzNlMWFmMTc2ZiIsInVpZCI6IjQ3NTc4ZmQzLThhNGEtNDk1YS05M2YxLWQ5NzZmYjdmY2Q0ZCIsImlhdCI6MTYzODk1MTcxNCwiZXhwIjoxNjM5MDM4MTE0fQ.4YkMNVW0ilhjilCkCgXzYNPgZja5A-QTC9S_MN5h9kg; Path=/; HttpOnly; Secure; SameSite=Lax; HttpOnly; Secure; SameSite=Lax
uid: 47578fd3-8a4a-495a-93f1-d976fb7fcd4d
###
GET http://localhost:5000/users/619d26efd0477d7c378d4f1f/articles
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOWUzNDU1NWExZGE4YzNlMWFmMTc2ZiIsInVpZCI6IjQ3NTc4ZmQzLThhNGEtNDk1YS05M2YxLWQ5NzZmYjdmY2Q0ZCIsImlhdCI6MTYzODk1MTcxNCwiZXhwIjoxNjM5MDM4MTE0fQ.4YkMNVW0ilhjilCkCgXzYNPgZja5A-QTC9S_MN5h9kg; Path=/; HttpOnly; Secure; SameSite=Lax
uid: 47578fd3-8a4a-495a-93f1-d976fb7fcd4d
###
GET http://localhost:5000/users/61af1b962b191365c7df2da5/demand
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOWUzNDU1NWExZGE4YzNlMWFmMTc2ZiIsInVpZCI6IjQ3NTc4ZmQzLThhNGEtNDk1YS05M2YxLWQ5NzZmYjdmY2Q0ZCIsImlhdCI6MTYzODk1MTcxNCwiZXhwIjoxNjM5MDM4MTE0fQ.4YkMNVW0ilhjilCkCgXzYNPgZja5A-QTC9S_MN5h9kg; Path=/; HttpOnly; Secure; SameSite=Lax
uid: 47578fd3-8a4a-495a-93f1-d976fb7fcd4d
###
GET http://localhost:5000/users/list
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOWUzNDU1NWExZGE4YzNlMWFmMTc2ZiIsInVpZCI6IjQ3NTc4ZmQzLThhNGEtNDk1YS05M2YxLWQ5NzZmYjdmY2Q0ZCIsImlhdCI6MTYzODk1MTcxNCwiZXhwIjoxNjM5MDM4MTE0fQ.4YkMNVW0ilhjilCkCgXzYNPgZja5A-QTC9S_MN5h9kg; Path=/; HttpOnly; Secure; SameSite=Lax
uid: 47578fd3-8a4a-495a-93f1-d976fb7fcd4d
###
GET http://localhost:5000/users/accept/61b0a8fa4c73491762eb5afb
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOWUzNDU1NWExZGE4YzNlMWFmMTc2ZiIsInVpZCI6IjQ3NTc4ZmQzLThhNGEtNDk1YS05M2YxLWQ5NzZmYjdmY2Q0ZCIsImlhdCI6MTYzODk1MTcxNCwiZXhwIjoxNjM5MDM4MTE0fQ.4YkMNVW0ilhjilCkCgXzYNPgZja5A-QTC9S_MN5h9kg; Path=/; HttpOnly; Secure; SameSite=Lax
uid: 47578fd3-8a4a-495a-93f1-d976fb7fcd4d
###
DELETE http://localhost:5000/users/619cc758e6235d7198fdef60
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOWUzNDU1NWExZGE4YzNlMWFmMTc2ZiIsInVpZCI6IjQ3NTc4ZmQzLThhNGEtNDk1YS05M2YxLWQ5NzZmYjdmY2Q0ZCIsImlhdCI6MTYzODk1MTcxNCwiZXhwIjoxNjM5MDM4MTE0fQ.4YkMNVW0ilhjilCkCgXzYNPgZja5A-QTC9S_MN5h9kg; Path=/; HttpOnly; Secure; SameSite=Lax
uid: 47578fd3-8a4a-495a-93f1-d976fb7fcd4d
###
DELETE http://localhost:5000/users/list/61b089b1dc27d598fef4f51f
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOWUzNDU1NWExZGE4YzNlMWFmMTc2ZiIsInVpZCI6IjQ3NTc4ZmQzLThhNGEtNDk1YS05M2YxLWQ5NzZmYjdmY2Q0ZCIsImlhdCI6MTYzODk1MTcxNCwiZXhwIjoxNjM5MDM4MTE0fQ.4YkMNVW0ilhjilCkCgXzYNPgZja5A-QTC9S_MN5h9kg; Path=/; HttpOnly; Secure; SameSite=Lax
uid: 47578fd3-8a4a-495a-93f1-d976fb7fcd4d