GET http://localhost:5000/users
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOWUzNDU1NWExZGE4YzNlMWFmMTc2ZiIsInVpZCI6ImZmOTRiZWU0LTQxNDgtNGIzYi05OGM2LThkMDdlMWQ0MTM3OCIsImlhdCI6MTYzOTAzODE3NSwiZXhwIjoxNjM5MTI0NTc1fQ.AxbyjYGU-DvYAacRkft4A8_PrwkeTisSZC1KGsUx3Xo; Path=/; HttpOnly; Secure; SameSite=Lax
uid: ff94bee4-4148-4b3b-98c6-8d07e1d41378
###
GET http://localhost:5000/users/619d26efd0477d7c378d4f1f/articles
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOWUzNDU1NWExZGE4YzNlMWFmMTc2ZiIsInVpZCI6ImZmOTRiZWU0LTQxNDgtNGIzYi05OGM2LThkMDdlMWQ0MTM3OCIsImlhdCI6MTYzOTAzODE3NSwiZXhwIjoxNjM5MTI0NTc1fQ.AxbyjYGU-DvYAacRkft4A8_PrwkeTisSZC1KGsUx3Xo; Path=/; HttpOnly; Secure; SameSite=Lax
uid: ff94bee4-4148-4b3b-98c6-8d07e1d41378
###
GET http://localhost:5000/users/61af1b962b191365c7df2da5/demand
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOWUzNDU1NWExZGE4YzNlMWFmMTc2ZiIsInVpZCI6ImZmOTRiZWU0LTQxNDgtNGIzYi05OGM2LThkMDdlMWQ0MTM3OCIsImlhdCI6MTYzOTAzODE3NSwiZXhwIjoxNjM5MTI0NTc1fQ.AxbyjYGU-DvYAacRkft4A8_PrwkeTisSZC1KGsUx3Xo; Path=/; HttpOnly; Secure; SameSite=Lax
uid: ff94bee4-4148-4b3b-98c6-8d07e1d41378
###
GET http://localhost:5000/users/list
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOWUzNDU1NWExZGE4YzNlMWFmMTc2ZiIsInVpZCI6ImZmOTRiZWU0LTQxNDgtNGIzYi05OGM2LThkMDdlMWQ0MTM3OCIsImlhdCI6MTYzOTAzODE3NSwiZXhwIjoxNjM5MTI0NTc1fQ.AxbyjYGU-DvYAacRkft4A8_PrwkeTisSZC1KGsUx3Xo; Path=/; HttpOnly; Secure; SameSite=Lax
uid: ff94bee4-4148-4b3b-98c6-8d07e1d41378
###
GET http://localhost:5000/users/accept/61b1dabc0f8eeb1631fb3361
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOWUzNDU1NWExZGE4YzNlMWFmMTc2ZiIsInVpZCI6ImZmOTRiZWU0LTQxNDgtNGIzYi05OGM2LThkMDdlMWQ0MTM3OCIsImlhdCI6MTYzOTAzODE3NSwiZXhwIjoxNjM5MTI0NTc1fQ.AxbyjYGU-DvYAacRkft4A8_PrwkeTisSZC1KGsUx3Xo; Path=/; HttpOnly; Secure; SameSite=Lax
uid: ff94bee4-4148-4b3b-98c6-8d07e1d41378
###
DELETE http://localhost:5000/users/619cc758e6235d7198fdef60
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOWUzNDU1NWExZGE4YzNlMWFmMTc2ZiIsInVpZCI6ImZmOTRiZWU0LTQxNDgtNGIzYi05OGM2LThkMDdlMWQ0MTM3OCIsImlhdCI6MTYzOTAzODE3NSwiZXhwIjoxNjM5MTI0NTc1fQ.AxbyjYGU-DvYAacRkft4A8_PrwkeTisSZC1KGsUx3Xo; Path=/; HttpOnly; Secure; SameSite=Lax
uid: ff94bee4-4148-4b3b-98c6-8d07e1d41378
###
DELETE http://localhost:5000/users/demand/61b1cd491aed49af18864d76
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOWUzNDU1NWExZGE4YzNlMWFmMTc2ZiIsInVpZCI6ImZmOTRiZWU0LTQxNDgtNGIzYi05OGM2LThkMDdlMWQ0MTM3OCIsImlhdCI6MTYzOTAzODE3NSwiZXhwIjoxNjM5MTI0NTc1fQ.AxbyjYGU-DvYAacRkft4A8_PrwkeTisSZC1KGsUx3Xo; Path=/; HttpOnly; Secure; SameSite=Lax
uid: ff94bee4-4148-4b3b-98c6-8d07e1d41378
###
DELETE http://localhost:5000/users/remove/61af1b962b191365c7df2da5
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOWUzNDU1NWExZGE4YzNlMWFmMTc2ZiIsInVpZCI6ImZmOTRiZWU0LTQxNDgtNGIzYi05OGM2LThkMDdlMWQ0MTM3OCIsImlhdCI6MTYzOTAzODE3NSwiZXhwIjoxNjM5MTI0NTc1fQ.AxbyjYGU-DvYAacRkft4A8_PrwkeTisSZC1KGsUx3Xo; Path=/; HttpOnly; Secure; SameSite=Lax
uid: ff94bee4-4148-4b3b-98c6-8d07e1d41378